// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-MetaBidding",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-MetaBidding", targets: ["AATKit-MetaBidding"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-GraviteRTB.git", exact: "3.18.0-beta3"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-MetaBidding",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    .product(name: "AATKit-GraviteRTB", package: "AATKit-GraviteRTB"),
                    "AATMetaBiddingAdapter",
                    "AATFBAudienceNetwork",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-MetaBidding"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATMetaBiddingAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/AATMetaBiddingAdapter.zip",
            checksum: "ee4b4c135b9be6ca975189df4b9f779e2c92984ffff24bfdd3f3aef04b2558d0"
        ),
        .binaryTarget(
            name: "AATFBAudienceNetwork",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/FBAudienceNetwork.zip",
            checksum: "0b4566d7f4e1d72a2dbd5c4d759dac6c3e9c3b95f7ac9dac6ec19b35675ac605"
        ),
    ]
)
